# Source Image
FROM docker.io/library/golang:1.25@sha256:d7098379b7da665ab25b99795465ec320b1ca9d4addb9f77409c4827dc904211

# Copy script
WORKDIR /certs
COPY certificates.sh .
RUN chmod +x ./certificates.sh

# Install minica
RUN go install github.com/jsha/minica@latest

# Container start command
CMD ["/certs/certificates.sh"]
