# Source Image
FROM docker.io/library/golang:1.25@sha256:ab1f5c47de0f2693ed97c46a646bde2e4f380e40c173454d00352940a379af60

# Copy script
WORKDIR /certs
COPY certificates.sh .
RUN chmod +x ./certificates.sh

# Install minica
RUN go install github.com/jsha/minica@latest

# Container start command
CMD ["/certs/certificates.sh"]
